version: '3.4'

services:
  apartmentsbilling.apiui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:8080
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - apartmant_billing_backend

networks:
  apartmant_billing_backend:
    driver: brige
    external: true
  
    